config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :cart_products, only: %i[new create edit update index]
  delete 'cart_products', to: 'cart_products#destroy_all', as: :destroy_all
  delete 'cart_products/:id', to: 'cart_products#destroy', as: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_product

  # validations
  validates :cart_product_id, :total, presence: true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  # validations
  validates :product_id, :quantity, :total, presence: true
  validates :product_id, uniqueness: { message: 'This product has already been added to the cart.' }
  validates :quantity, numericality: { only_integer: true }
end

app/models/product.rb
class Product < ApplicationRecord
  # validations
  validates :product_code, :name, :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_products_controller.rb
class CartProductsController < ApplicationController
  def index
    @cart_products = CartProduct.all
    @totals = []
    @prods = []
    @cart_products.each do |product|
      @totals << product.total
      @prods << Product.find(product.product_id)
    end
    @total = @totals.sum
  end

  def create
    values = params['cart_product'].values
    @product = Product.find(values[0])
    total = total(@product, values[1].to_i)
    @cart_product = CartProduct.new(product_id: @product.id, quantity: values[1].to_i, total: total)
    redirect_to cart_products_path if @cart_product.save!
  end

  def edit
    @cart_product = CartProduct.find(params[:id])
  end

  def update
    values = params['cart_product'].values
    @product = Product.find(values[0])
    @cart_product = CartProduct.find(params[:id])
    if params[:cart_product][:quantity].to_i <= 0
      @cart_product.destroy!
    else
      total = total(@product, params[:cart_product][:quantity].to_i)
      @cart_product.update(quantity: params[:cart_product][:quantity].to_i, total: total)
      @cart_product.save!
    end
    redirect_to cart_products_path
  end

  def destroy_all
    CartProduct.destroy_all
    redirect_to cart_products_path, status: :see_other
  end

  def destroy
    @cart_product = CartProduct.find(params[:id])
    @cart_product.destroy
    redirect_to cart_products_path, status: :see_other
  end

  def total(product, quantity)
    case product.product_code
    when 'GR1'
      free_green_tea(product.price, quantity)
    when 'SR1'
      reduced_price_strawberries(product.price, quantity)
    when 'CF1'
      drop_price_coffee(product.price, quantity)
    end
  end

  def free_green_tea(price, quantity)
    if quantity > 2
      quantity_divided = quantity / 2.0
      price * quantity_divided.round
    elsif [1, 2].include?(quantity)
      price
    else
      0
    end
  end

  def reduced_price_strawberries(price, quantity)
    if quantity > 2
      discount = 0.9
      (price * discount) * quantity
    else
      price * quantity
    end
  end

  def drop_price_coffee(price, quantity)
    if quantity > 2
      discount = 2.0 / 3
      (price * discount) * quantity
    else
      price * quantity
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @products = Product.all
    @cart_products = []
  end

  def free_green_tea(cart_product)
    if cart_product.quantity > 2
      quantity = cart_product.quantity / 2.0
      cart_product.total * quantity.round
    elsif cart_product.quantity == 1 || cart_product.quantity == 2
      cart_product.total
    else
      0
    end
  end

  def reduced_price_strawberries(cart_product)
    quantity = cart_product.quantity
    if quantity > 2
      discount = 0.9
      (cart_product.total * discount) * quantity
    else
      cart_product.total * quantity
    end
  end

  def drop_price_coffee(cart_product)
    quantity = cart_product.quantity
    if quantity > 2
      discount = 2.0 / 3
      (cart_product.total * discount) * quantity
    else
      cart_product.total * quantity
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @cart_products = []
    @cart_product = CartProduct.new
  end
end

app/views/cart_products/index.html.erb
<div class="container" data-controller="product">
  <div class="row justify-content-center vh-100 align-items-center">
    <div class="col-12 col-lg-6">
      <div class="d-flex justify-content-center">
        <h4>Shopping Cart</h4>
      </div>
        <div class="product-container">
          <% @cart_products.each_with_index do |product, index| %>
          <div class="product-card">
            <div class="product-image">
              <%= image_tag @prods[index].photo_path %>
            </div>
            <div class="product-details">
              <p>Qty: <%= product.quantity %></p>
              <p><%= @prods[index].name %></p>
            </div>
            <div class="product-total">
              <p>Subtotal = <%= product.total %>€</p>
            </div>
            <div>
              <div class="blue-btn my-2" data-action="click->product#addQuantity">
                <p>Edit quantity</p>
              </div>
              <div class="d-none">
                <%= simple_form_for [product] do |f| %>
                <%= f.hidden_field :id, value: @prods[index].id %>
                <div class="product-input">
                  <%= f.text_field :quantity %>
                  <%= f.submit value:"Submit"%>
                </div>
                <% end %>
              </div>
              <%= link_to destroy_path(product.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
                <div class="orange-btn my-2">
                    <p>delete</p>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>
        </div>
      <div class="d-flex justify-content-center">
        <h4>TOTAL: <%= @total  %>€</h4>
      </div>
      <div class="d-flex justify-content-between">
        <div class="orange-btn p-2">
        <%= link_to "Delete All",
        destroy_all_path,
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
        %>
        </div>
        <div class="green-btn p-2">
        <%= link_to "Continue shopping", root_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CashRegisterAmenitiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container" data-controller="product">
  <div class="row justify-content-center vh-100 align-items-center">
      <div class="col-12 col-lg-6">
        <div class="d-flex justify-content-center">
          <h4>Products</h4>
        </div>
        <div class="product-container">
          <% @products.each do |product| %>
          <div >
            <div class="product-image">
              <%= image_tag product.photo_path %>
            </div>
            <div class="product-details">
              <p><%= product.name %></p>
              <p><%= product.price %>€</p>
            </div>
            <div class="blue-btn my-2" data-action="click->product#addQuantity">
              <p>Add quantity</p>
            </div>
            <div class="d-none">
              <%= simple_form_for [@cart_product] do |f| %>
              <%= f.hidden_field :id, value: product.id %>
              <div class="product-input">
                <%= f.text_field :quantity %>
                <%= f.submit value:"Submit"%>
              </div>
              <% end %>
            </div>
          </div>
          <% end %>
        </div>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-container">
  <div class="container">
    <div class="navbar-items">
      <div>
        <%= link_to root_path do %>
          <h2>Cash Register</h2>
        <% end %>
      </div>
      <div>
        <%= link_to cart_products_path do %>
          <i class="fas fa-shopping-cart"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>